- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: moongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb
    ansible.builtin.package:
      name: mongod-org
      state: present

  - name: start and enable mongod
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace:  '0.0.0.0'
    
  - name: start and enable mongod
    ansible.builtin.service:
      name: mongod
      state: restarted
